// Scene Reports types — per-scene research-deck generation introduced in
// STO-1066 / STO-1067. Mirror the backend serializer shapes from
// `creative_hub/scene_report_serializers.py`.

export interface SceneReportEnvelopeSection {
  section_id?: string;
  section_title?: string;
  sort_order?: number;
  viz_type?: string;
  data?: Record<string, unknown> | null;
}

export interface SceneReportEnvelopeCitation {
  ref_id?: string;
  source?: string;
  accessed?: string;
  url?: string;
  title?: string;
}

/**
 * Envelope JSON returned in `SceneGeneratedReport.data`. Generated by the
 * LangGraph pipeline. Most fields are optional — legacy reports written before
 * STO-1066 will only have `legacy_markdown` (or sections[0].data.prose.markdown)
 * with `tab_type === "legacy_markdown"`.
 */
export interface SceneReportEnvelope {
  tab_key?: string;
  tab_type?: string;
  tab_display_name?: string;
  executive_summary?: string;
  structured_data?: Record<string, unknown> | null;
  sections?: SceneReportEnvelopeSection[];
  citations?: SceneReportEnvelopeCitation[];
  scene_id?: number;
  scene_order?: number;
  scene_name?: string;
  generated_at?: string;
  /** Legacy fallback — set when tab_type === "legacy_markdown". */
  legacy_markdown?: string;
  // Allow any additional structured payload keys (LLM may add them).
  [key: string]: unknown;
}

export interface SystemSceneReportType {
  id: number;
  name: string;
  display_name: string;
  system_role?: string;
  prompt_template?: string;
  schema?: Record<string, unknown> | null;
  dependencies?: string[];
  handler?: string;
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface CustomSceneReportType {
  id: number;
  project: string;
  project_name?: string;
  name: string;
  display_name: string;
  system_role?: string;
  prompt_template?: string;
  schema?: Record<string, unknown> | null;
  dependencies?: string[];
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}

export type SceneReportKind = "system" | "custom";

export interface SceneGeneratedReport {
  id: number;
  scene: number;
  report_type: SceneReportKind;
  /** Backend `report_id` references SystemSceneReport / CustomSceneReport PK. */
  report_id: number;
  report_name?: string | null;
  data: SceneReportEnvelope | null;
  project_context?: Record<string, unknown> | null;
  status: "pending" | "success" | "failed" | string;
  created_at: string;
  updated_at: string;
}

/** Returned by GET /scenes/<id>/reports/list/. */
export interface SceneGeneratedReportListResponse {
  scene_id: number;
  scene_name?: string;
  scene_order?: number;
  reports: SceneGeneratedReport[];
  count: number;
}

/** Returned by GET /scenes/<id>/report-types/. */
export interface SceneAvailableReportTypes {
  scene_id: number;
  scene_name?: string;
  scene_order?: number;
  available_reports: {
    system: SystemSceneReportType[];
    custom: CustomSceneReportType[];
  };
}

/** Body for POST /scenes/<id>/reports/generate/. The backend keys on `report_name`. */
export interface SceneReportGenerateRequest {
  report_type: SceneReportKind;
  report_name: string;
  force_regenerate?: boolean;
}

export interface SceneReportGenerateResponse {
  message: string;
  report: SceneGeneratedReport;
  action: "generated" | "regenerated" | "existing";
  error?: string;
}

export interface SceneReportBulkGenerateRequest {
  reports: Array<{ report_type: SceneReportKind; report_name: string }>;
  force_regenerate?: boolean;
}
